name: lora-sd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch>=2.0.0
    - diffusers>=0.16.0
    - transformers>=4.30.0
    - accelerate>=0.20.3
    - peft>=0.3.0
    - datasets>=2.10.1
    - Pillow>=9.0.0
    - onnxruntime>=1.15.1
    - tqdm>=4.64.0
    - PyYAML>=6.0
